rootLogger: INFO, console

logger:
  service.statsd: DEBUG
  plugin.statsd.StatsdPlugin: DEBUG

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
